version: '3.1'
services:
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - 31000:80
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
    volumes:
     - db-vol:/var/lib/mysql
volumes:
  db-vol:
